Hangman Project
brprotsenko/NIX_Java_education_Protsenko_Bogdan pull request #5
Opened 2021-12-01 19:07 UTC by brprotsenko

Hangman Project - Stage 1

Hangman Project - Stage 2

Hangman Project - Stage 3

Hangman Project - Stage 4

Hangman Project ----

Hangman Project Stage-8

2021-12-03 23:45 UTC, maxsomochkin requested changes

2021-12-03 23:45 UTC, maxsomochkin commented on src/nix/education/java/hangman/Hangman.java
> +public class Hangman {
Оставь название этого класса Main. Создай Отдельный класс Hangman. В нем создай методы. В методе main создай объект Hangman. и из него вызывай методы.

2021-12-03 23:45 UTC, maxsomochkin commented on src/nix/education/java/hangman/Hangman.java
> +        for(int i = 1; i>i-1;i++){
Цикл в отдельный метод в класс Hangman.

2021-12-03 23:45 UTC, maxsomochkin commented on src/nix/education/java/hangman/Hangman.java
> +    static void hangman() {
Переименуй метод так, чтобы он описывал  действие, которое он выполняет и помести его в класс Hangman.

2021-12-03 23:45 UTC, maxsomochkin commented on src/nix/education/java/hangman/Hangman.java
> +        for(int i = 8; i >= 1;){
Цикл  в отдельный метод вынеси

2021-12-06 19:37 UTC, asrubel commented on src/nix/education/java/hangman/Main.java
> +public class Main extends Hangman {
главный класс ничего не должен наследовать - просто  в методе main создавай объекты и управляй ими, просто убери это наследование

2021-12-06 19:37 UTC, asrubel approved these changes

2021-12-06 20:17 UTC, merged